### ISSUE TITLE
Proposal for tree:import or a tree:conditionalImport on a tree:Node

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/specification#17]
This came up in the Linked Connections 2.0 discussion today: we need to be able to describe when a collection fragments based on a type of entity. Therefore we propose to have a `tree:embed` on a `tree:Node`, where other files can be embedded when a client is looking for an entity on a certain property path.

For example:
```turtle
<currentpage> a tree:Node ;
	tree:qualifiedImport [
		tree:path lc:departureStop ;
		tree:import <stops> 
],[
		tree:path lc:arrivalStop ;
		tree:import <stops> 
],[
		tree:path (gtfs:trip gtfs:route ) ;
		tree:import <routes> 
]  .
```
This leaves the stops and routes out of a connections collection, and instead tells a client, when interested in these entities, to discover them at another location.

When you always need to import a file with a certain view, you can simply use:
```turtle
<currentpage> a tree:Node ;
	tree:import <stops> .
```

**Comment by hdelva** [comment]
I think that so far `tree:path` has mostly been a filter on which triples to consider from an external resource, right? Because it seems like in this context, it's the other way around, and it describes where to find more information about the current resource. 

Apart from that, I like it!

**Comment by pietercolpaert** [comment]
@hdelva Good point! So `tree:path` gets a different meaning in a tree:Embedding than in a tree:Relation. I don’t think this is a huge issue though. Or should we consider different predicates?

**Comment by pietercolpaert** [comment]
tree:embed → tree:qualifiedImport?

**Comment by pietercolpaert** [comment]
import and conditionalImport added to the spec.
