### ISSUE TITLE
Out of band index fragments

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/specification#23]
Out of band index fragments or TREE overlays could serve the purpose of overlaying an index on another property out of band (thus also allowing third parties to contribute other indexes over the same set of fragments).

Take for example a geospatial TREE where also zip codes are given. A third party may be interested in querying over ZIP codes and may speed up the querying by adding an index.

## Example design

```turtle
<C> a tree:Collection ;
        tree:view <zipcodeOverlay> ;
        tree:relation <R1>, <R2>, <R3> .

<R1> a tree:EqualsRelation ;
        tree:path ex:zipCode ;
        tree:value "8000"^^xsd:string ;
        tree:node <geospatialtree/N1>,<geospatialtree/N2>,<geospatialtree/N3> . #Three nodes from a different tree containing zip codes 8000
```

Over here, the client needs to also follow all other relations that will be present in the N1, N2 and N3 from the original fragmentation. While this makes sense in this particular example, it may not always make sense to have to rely on the further hypermedia controls from the third party whom you are overlaying. Therefore, we introduce the concept of a `tree:Overlay`:

```turtle
<C> a tree:Collection ;
        tree:view <geospatialtree> .
<zipcodeOverlay> a tree:Overlay ;
        tree:overlays <geospatialtree> ;
        tree:relation <R1>, <R2>, <R3> .

<R1> a tree:EqualsRelation ;
        tree:path ex:zipCode ;
        tree:value "8000"^^xsd:string ;
        tree:node <geospatialtree/N1>,<geospatialtree/N2>,<geospatialtree/N3> . #Three nodes containing zip codes 8000
```

**Comment by julianrojas87** [comment]
Could this be related to [this LDES issue](https://github.com/SEMICeu/LinkedDataEventStreams/issues/4)?
