### ISSUE TITLE
Bring the dark theme into the 21th century

### ISSUE THREAD

**Issue by hdelva** [TREEcg/specification#29]
The current styling contains the following:

```
@media (prefers-color-scheme: dark)
:root {
    --text: #ddd;
    --bg: black;
}
```

The pure black background is giving off some high-contrast Windows XP vibes, and makes the spec pretty hard to read. I'm pretty sure browsers like Firefox and Brave have a dark theme set by default now, so this pure-black background is the default on these browsers as well.

I propose to either drop those media queries altogether, or set the background to a dark grey.

**Comment by hdelva** [comment]
There doesn't appear to be any way to disable the dark theme at the moment, or to tweak the CSS at all. There's an open issue on the bikeshed repo at the moment, guess we'll wait.

https://github.com/tabatkins/bikeshed/issues/1806

**Comment by matthieubosquet** [comment]
@hdelva sorry if my formulation of the issue is a bit misleading, but what I refer to as missing is a UI style switch.

There is a way to disable darkmode altogether in the metadata block:

```
<pre class='metadata'>
Boilerplate: style-darkmode off
</pre>
```

See also: https://tabatkins.github.io/bikeshed/#metadata
