### ISSUE TITLE
4.1 traversal

### ISSUE THREAD

**Issue by Dexagod** [TREEcg/specification#33]
The start of [section 4.1](https://treecg.github.io/specification/#multiple-views) is a tad difficult to understand.
The different relations and their connection to the travesal process are not even mentioned.
The way the different parts of a relation are presented also does not properly give an overview of the structure.

A small image here could be of use

**Comment by pietercolpaert** [comment]
Can you propose a way to represent this in an image? Can be a quick sketch on paper, I’m willing to recreate this in the same style as the first image then.

**Comment by Dexagod** [comment]
maybe we could approach this with a jsonld snippet of the relation, and a comparison operation in latex math, and align the colors between the 2?
In any case it should make clear which part of the relation takes care of which part of the operation.
This then ties into #35, as when it is clear which part of the relation affects which part of the traversal, the fallbacks when missing this part of the relation become self-explanatory.

**Comment by pietercolpaert** [comment]
Rewritten in new spec
