### ISSUE TITLE
4.2 Fallback

### ISSUE THREAD

**Issue by Dexagod** [TREEcg/specification#35]
I find that this section reads very difficult sometimes generally.

I would find it more easy to process if it were structured for the attributes:

If we miss X, then the triples in the page indicate Y, so this must be processed as Z.

e.g.

When no tree:path is defined, the relation comparison is specified for ALL triple object values in a member, as the relation path preficate indicates the value in the member we are looking for.
Because of this,  the tree:value MUST be compared to all members’ triples that can be compared to the tree:value as defined by the type of the relation (or when no members or collection are defined, on every triple in the page). When due to rdfs:range incompatibility, the object cannot be compared, the object will not be considered for comparison.

**Specific issue:**

When there is no tree:shape given, then this collection may contain any kind of triple and can not be automatically pruned in the source selection. This may however still be useful in triple-based collections.

-> Is this true? We can prune if we have a relation with a path `firstname`, when querying for a prefix value for the `firstname` property.

**Comment by pietercolpaert** [comment]
This issue needs more in-depth aligning - let’s discuss this in a call

**Comment by pietercolpaert** [comment]
Rewritten in new spec
