### ISSUE TITLE
Add snippet examples in compatibility section (3.3) and push towards the end

### ISSUE THREAD

**Issue by julianrojas87** [TREEcg/specification#39]
I would add small snippet (RDF) examples to each one of the compatible specifications mentioned in section 3.3. E.g.:

```turtle
<A> a dcat:Distribution;
   dcat:accessURL <C1>;
   dcat:conformsTo tree: .
   
<C1> a tree:Collection .
...   
```

Also put this section after TREE has been explained better.

**Comment by pietercolpaert** [comment]
I’m also thinking maybe the tree:Collection should be a dcat:Dataset while the tree:Node of the view should probably be the dcat:Distribution

**Comment by pietercolpaert** [comment]
DCAT is now in discovery
