### ISSUE TITLE
Rewrite 2. imports

### ISSUE THREAD

**Issue by brechtvdv** [TREEcg/specification#41]
(e.g., the resulting page contains elements without materialized WKT strings, which however can be fetched from the import)
must be moved to the first part of the paragraph:
When defined as part of a tree:Node, this document always needs to be fetched when processing this Node, e.g., the resulting page contains elements without materialized WKT strings, which however can be fetched from the import.
When defined as part of the tree:Relation, one MUST fetch the import when the relation needs to be correctly evaluated.

**Comment by brechtvdv** [comment]
tree:path with a property path ... -> that indicates the resource elements in the imported resource contain

**Comment by pietercolpaert** [comment]
Related: #32

**Comment by brechtvdv** [comment]
I was wrong with re-ordening the first paragraph.

Only the tree:path description needs to be fixed (see commit)
