### ISSUE TITLE
Do we support ShEx on tree:shape?

### ISSUE THREAD

**Issue by julianrojas87** [TREEcg/specification#48]
Wondering if a TREE client should also be able to interpret [ShEx](https://shex.io/) as a way to describe members data shape, via the `tree:shape` property of a collection. If so, it should also be mentioned.

**Comment by pietercolpaert** [comment]
Good point. I didn’t investigate it yet, but if we want to be compatible with Shape Trees (`st:validatedBy`), then yes, we need to support shex. `tree:path` however will always remain a SHACL property path.

**Comment by pietercolpaert** [comment]
@woutslabbinck added an example in here!

**Comment by pietercolpaert** [comment]
We’re going to change the tree:shape to also support ShEx, so you can choose which one you use.

**Comment by pietercolpaert** [comment]
I added a small note in the part on the shape: saying the for compatibility with Solid, you could also support ShEx.
