### ISSUE TITLE
Summaries of multiple tree:Nodes

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/specification#6]
Placeholder: how do we describe summaries?

**Comment by julianrojas87** [comment]
Should summaries be even described by TREE? 
If so then `prov:wasDerivedFrom` or the more specific `pav:derivedFrom` predicates could be used in this case.
Other than having provenance about how the summary has been derived, what other use cases would this be needed for?

**Comment by pietercolpaert** [comment]
Related note: https://github.com/SEMICeu/LinkedDataEventStreams/issues/4

**Comment by pietercolpaert** [comment]
I’ll close this one: summaries will be a different `tree:Collection`
