### ISSUE TITLE
Elaborate TREE Example

### ISSUE THREAD

**Issue by pbonte** [TREEcg/specification#61]
I think currently the spec is missing a more in depth example of how a dataset described with TREE looks like.
It would be beneficial to include, next to the figure, an example of how such dataset would look like.

An example showing a collection with multiple members and one or more views would help. For me it was unclear what the result implied of following a certain view. So an additional example that shows the content of the collection after following a certain view might be helpful for others as well.
(For me it was not clear that the result was the same collection but with different members.)

**Comment by pietercolpaert** [comment]
This has been added to the spec!
