### ISSUE TITLE
Configurable membership path

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/specification#65]
If we don’t want to repeat tree:member if another property is used to indicate the containment

E.g.,:
 * dcat:Catalog → dcat:dataset
 * hydra:Collection → hydra:member
 * LDP collections
 * SKOS in scheme
 * ...

## Proposal

`tree:membershipPath` with `rdfs:range` a shacl path and with `rdfs:domain` a `tree:Node`

**Comment by julianrojas87** [comment]
So I understand this property is to avoid redundant triples when dealing with compatible collections and facilitating clients to quickly know where to look for members.

I guess this would be an optional property, that whenever not present, default behavior should be to first look for `tree:member` and any other property that could indicate membership (`hydra:member`, `skos:inScheme`, etc)

**Comment by pietercolpaert** [comment]
Yes indeed. I think this would be interesting to make sure TREE clients can also work on top of existing APIs
