### ISSUE TITLE
Missing 'Rootnode' and 'View'

### ISSUE THREAD

**Issue by ArneVanDerStuyft** [TREEcg/specification#67]
In the current specification, tree:view is a property of a node which is necessary to navigate. 

However, during the OSLO-LDES trajectory, it became clear that two additional classes are required: 

1. A class tree:View which is an index/invariant/organisation who indicates how someone can navigate through a collection. 

2. A Rootnode: is the startpage, who contains members itself, an by whose linked pages all members of the collection can be retrieved.

**Comment by pietercolpaert** [comment]
Thi has been resolved in this commit: https://github.com/TREEcg/specification/commit/6b267895a01cb7aea975884861c48196cec49cc3

It introduces a tree:ViewDescription class that is a subclassof dcat:DataService and can be linked from any tree:Node with tree:viewDescription predicate. A root node (which is not specifically typed as all tree:Nodes linked with tree:view can be regarded as a root node from the client’s perspective) can be found by following the dcat:endpointURI on top of this tree:ViewDescription.
