### ISSUE TITLE
Relations can be represented in Link header

### ISSUE THREAD

**Issue by sandervd** [TREEcg/specification#70]
When a tree:Node is retrieved over the web, it might be useful to include the relations defined in it as a Link header.
This would allow traversing relations without fetching the contents (HEAD requests), as well as speed up traversal,
as document relations can be followed/prefetched before the actual contents is parsed.

This would benefit from the implementation of #64.

**Comment by pietercolpaert** [comment]
At this moment there is one way in TREE to extract relations--through the body of the page--and it’s simple. If we were to add extra complexity in TREE on how to extract relations, and multiple ways to extract those, I think the complexity raises (i.e., what if the headers are not the same as the in-body relations? Or, how do you fully qualify the relation in the headers?) then it needs to come with a clear advantage.

The advantage you mention would be speeding up traversal speed as before you parse the content, you can already know the links. I would however argue that if a server would want to create a search tree like that to make it faster for clients to parse relations, then these relations would be part of the previous page.

So I would close this issue, and #64 as well, in favor of keeping things simple: if you would encounter a case like this, I think it would mean you need to rethink your search tree’s design.

If you disagree, feel free to re-open and then we make it a discussion during a CG meeting.
