### ISSUE TITLE
SHACL shape, data schema question.

### ISSUE THREAD

**Issue by xdxxxdx** [TREEcg/specification#81]
Imagine, there is an LDES server under development.

Is it the responsibility for the LDES Server to validate the shape of the ingesting member?
If yes, how the server should behave if the shape changes?

Or it is the job for Client to prune out the Not valid members? I mean after the synchronization, the client just does another pipeline prune out all the not valid member?

Thanks

**Comment by pietercolpaert** [comment]
I’d say it’s the responsibility of the data owner to properly describe the data that is part of the LDES, and that way the data in that LDES will be valid according the shape without the server first needing to reject a member.

Depending on how the server works, the server could also have an open-ended write interface. A server could then decide to validate the members at write-time, and reject user input that is invalid according to the documented shape.
