### ISSUE TITLE
Mention tree:InBetweenRelation in the SPEC's vocabulary

### ISSUE THREAD

**Issue by xdxxxdx** [TREEcg/specification#82]
Hello @pietercolpaert,

I see the `tree:InBetweenRelation` relation is mentioned in the https://github.com/TREEcg/specification/blob/master/tree.ttl.
But cannot find it in https://treecg.github.io/specification/. ([Draft Community Group Report](https://www.w3.org/standards/types#CG-DRAFT), 25 May 2023)

Might be also good add `tree:InBetweenRelation`  to the Chapter https://treecg.github.io/specification/#Relation

Thanks

**Comment by pietercolpaert** [comment]
The purpose of the tree:InBetweenRelation was planned to be to compare xsd:duration datatypes, or maybe ISO8601 periods such as `2003-02-15T00:00:00Z/P2M` (this interval ends two calendar months later at 2003-04-15T00:00:00Z which is 59 days later). The usefulness towards current use cases will be very limited.

For indicating a tree:node contains members between 2 separate values, you must use 2 relations towards the same node.

**Comment by xdxxxdx** [comment]
Thanks @pietercolpaert !
