### ISSUE TITLE
Add Version control 

### ISSUE THREAD

**Issue by xdxxxdx** [TREEcg/specification#84]
As the [GitHub - Informatievlaanderen/VSDS-Testbed](https://github.com/Informatievlaanderen/VSDS-Testbed)  is developed for testing against [The TREE hypermedia specification](https://treecg.github.io/specification/).   It might be a good idea to have version control of the SPEC (includes historical versions), then the testbed could always have a valid reference link pointing to the SPEC.

Also projects developed for implementing TREE also can benefit from it, when using `dct:conforms` in the metadata.

**Comment by kkostov** [comment]
This would be very helpful indeed!

**Comment by pietercolpaert** [comment]
From the call decision: 

Let’s add a semantic version changelog, but let’s indicate that our goal is to have no breaking changes: we are working towards a 1.0 version that must remain backwards compatible forever

**Comment by pietercolpaert** [comment]
As this is still not fully in place, I’d like to propose a change: the W3C specifications usually work with changelogs based on decisions that were taken, and with a version of a spec based on a certain data of the latest consensus.

I’d propose using the releases functionality on Github for listing the decisions that have been taken and the time of that meeting.
