### ISSUE TITLE
Client and Server Implementation Guidelines for Common HTTP Use cases

### ISSUE THREAD

**Issue by kkostov** [TREEcg/specification#92]
When creating a production implementation of the spec (both client and server-side), it may be beneficial to have access to a set of guidelines on how to tackle common technical implementation details:

* Handling of redirects along the graph
* Handling upgrade of HTTP to HTTPS
* CORS
* The need to pass custom headers in case of scenarios like authentication or API limits?
* ...

**Comment by pietercolpaert** [comment]
Found an interesting example for this: https://iiif.io/api/discovery/1.0/#4-network-considerations

**Comment by kkostov** [comment]
@pietercolpaert this is an excellent example, I like that the guidelines also appear as a SHOULD.

**Comment by sandervd** [comment]
- A server should define a default Accept header (e.g. if no accept is defined, return content type Turtle)

**Comment by pietercolpaert** [comment]
Related to #111 and #112 , I think it makes sense to do this in specifications that use the TREE specification that are directed towards server implementers. TREE should not do this as it is directed towards clients.
